spring:
  profiles:
    active: gke
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1/microservice?useUnicode=true&characterEncoding=utf8&useSSL=false
    name: null
    username: gke-demo
    password: ${GKE_DEMO_DB_PASS}
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: false
