spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -Duser.timezone=Europe/Zurich -Dspring.profiles.active=gke
            - name: GKE_DEMO_DB
              valueFrom:
                configMapKeyRef:
                  name: database-env-cm
                  key: GKE_DEMO_DB
            - name: GKE_DEMO_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: database-env-cm
                  key: GKE_DEMO_DB_HOST
            - name: GKE_DEMO_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: database-env-cm
                  key: GKE_DEMO_DB_USER
            - name: GKE_DEMO_DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: database-env-cm
                  key: GKE_DEMO_DB_PASS
            - name: CLOUD_SQL_INSTANCE
              valueFrom:
                configMapKeyRef:
                  name: database-env-cm
                  key: CLOUD_SQL_INSTANCE